In [ ]:
# ML Zoomcamp Module 1 Homework - Tristan Kilper

In [2]:
import pandas as pd

In [ ]:
# Q1

In [3]:
pd.__version__

'2.3.3'

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [8]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [ ]:
# Q2

In [7]:
df.shape[0]

9704

In [ ]:
# Q3

In [10]:
df[["fuel_type"]].drop_duplicates().shape[0]

2

In [ ]:
# Q4

In [16]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
# Q5

In [14]:
df.query('origin == "Asia"')[["fuel_efficiency_mpg"]].max()

fuel_efficiency_mpg    23.759123
dtype: float64

In [ ]:
# Q6

In [18]:
df6 = df[["horsepower"]]
df6.median()

horsepower    149.0
dtype: float64

In [24]:
df6.value_counts().head(1)

horsepower
152.0         142
Name: count, dtype: int64

In [27]:
df6 = df6.fillna(152.0)

In [28]:
df6.median()

horsepower    152.0
dtype: float64

In [ ]:
# Q7

In [30]:
df7 = df.query('origin == "Asia"')

In [31]:
df7 = df7[["vehicle_weight","model_year"]]

In [32]:
df7 = df7.head(7)

In [34]:
import numpy as np

In [35]:
X = np.array(df7)

In [36]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [38]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [45]:
XTX = X.T.dot(X)

In [46]:
iXTX = np.linalg.inv(XTX)

In [47]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [48]:
r = iXTX.dot(X.T)

In [50]:
r = r * y

In [51]:
r

array([[-0.14432288, -0.11230828,  0.29810794, -0.36245398, -0.16251372,
        -0.06075771,  0.55811286],
       [ 0.28890053,  0.2560879 , -0.37871378,  0.59305003,  0.30835783,
         0.16679975, -0.72957556]])

In [52]:
r.sum()

np.float64(0.5187709081074016)